
version: '{build}.0.0-dev'
configuration: Release
os: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
environment:
  project_name: Spatial
  library_project_file: 'src\%project_name%\%project_name%.csproj'
  tests_project_file: 'tests\%project_name%.Tests\%project_name%.Tests.csproj'
  website_project_file: 'src\%project_name%.WebApplication\%project_name%.WebApplication.csproj'

# Override the 'version' if this is a GH-tag-commit -or- this is a custom branch (i.e not 'master').
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq $TRUE -and $env:APPVEYOR_REPO_BRANCH -eq 'master')
      { 
          Write-Host " !! Commit is Tagged and branch is 'master' - forcing build version to tag-value." -ForegroundColor Red; 
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))
                                       
before_build:
  - dotnet --info
  - dotnet restore 

build_script:
  - dotnet build -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%

test_script:
  - dotnet test %tests_project_file% -c %CONFIGURATION% -v normal --no-build
  - dotnet pack %library_project_file% -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION% --no-build

after_test:
  - dotnet publish %website_project_file% -c %CONFIGURATION% -o %appveyor_build_folder%\website

artifacts:
  - path: '**\*.nupkg'
  - path: website

# Myget -> master and not tagged.
# Nuget -> master and tagged.
# Website -> master and tagged.
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/pk-development/api/v2/package
    api_key:
      secure: 36bcjhroAjclbHs7e7oh6Hsv4lokADI6xaQcCYZmux2Sdu/IIoktFc9ORK3DTdKo
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: false
  - provider: NuGet
    api_key:
      secure: jfcUvHZhgnUboplqTBDWr8mG5PIlrgBv5TA2fhhop4ZSiDxskyy+RtYyeHoduJFR
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: WebDeploy
    server: https://spatialservices.scm.azurewebsites.net:443/msdeploy.axd?site=spatialservices
    website: spatialservices
    username: $spatialservices
    artifact: website
    password:
      secure: 0vcr+FUbAyn003aQJS6GiehOL58lMwAwHZiESh3cyBxZJgOy2qNtbVjelE9HzwICzel5bV816Se6DYdy03OJkA==
    remove_files: true
    on:
      branch: master
      appveyor_repo_tag: true

cache:
  - packages -> **\packages.config
